const logolistMap = [
    {
        name:'开源社',
        img:'logo4.jpg',
    },
    {
        name:'oschina',
        img:'logo5.jpg',
    },
    {
        name:'思否',
        img:'logo6.jpg',
    },
    {
        name:'xlab',
        img:'logo7.jpg',
    },
    {
        name:'北京大学',
        img:'logo8.jpg',
    },
    {
        name:'中国人民大学',
        img:'logo29.jpg',
    },
    {
        name:'清华大学',
        img:'logo20.jpg',
    },
    {
        name:'北京工业大学',
        img:'logo9.jpg',
    },
    {
        name:'北京理工大学',
        img:'logo11.jpg',
    },
    {
        name:'北京信息科技大学',
        img:'logo12.jpg',
    },
    {
        name:'华中科技大学',
        img:'logo17.jpg',
    }, 
    {
        name:'中国科学院大学',
        img:'logo28.jpg',
    }, 
    {
        name:'南开大学',
        img:'logo19.jpg',
    }, 
    {
        name:'天津大学',
        img:'logo23.jpg',
    }, 
    {
        name:'中国科学技术大学',
        img:'logo27.jpg',
    },
    {
        name:'复旦大学',
        img:'logo14.jpg',
    },
    {
        name:'同济大学',
        img:'logo24.jpg',
    },
    {
        name:'上海交通大学',
        img:'logo21.jpg',
    },
    {
        name:'华东师范大学',
        img:'logo16.jpg',
    },
    {
        name:'上海科技大学',
        img:'logo22.jpg',
    },
    {
        name:'西安交通大学',
        img:'logo26.jpg',
    },
    {
        name:'西安电子科技大学',
        img:'logo25.jpg',
    },
]

export default logolistMap